# -*- coding: utf-8 -*-
"""Contenido del sitio de Grupo Arcondec, en espanol e ingles.

Los textos son los de arcondec.mx, transcritos literalmente. Si hay que
cambiar una frase, se cambia AQUI y se vuelve a ejecutar `python3 tools/build.py`.

Cada pagina existe en dos idiomas con URL propia:
    ES  ->  /nosotros.html
    EN  ->  /en/about.html
"""

# --------------------------------------------------------------------------
# Datos de contacto (identicos en ambos idiomas salvo el correo de ventas)
# --------------------------------------------------------------------------
CONTACT = {
    "address": "Calle del Gran Parque 419, Cumbres 2o, 64610 Monterrey, N.L.",
    "street": "Calle del Gran Parque 419, Cumbres 2o",
    "city": "Monterrey",
    "region": "NL",
    "zip": "64610",
    "phone1": "81 1934 1192",
    "phone2": "81 1934 1194",
    "mobile": "(55) 3032 6595",
    "phone1_tel": "+528119341192",
    "phone2_tel": "+528119341194",
    "mobile_tel": "+525530326595",
    "mail_info": "info@arcondec.mx",
    "mail_sales_es": "ventas@arcondec.mx",
    "mail_sales_en": "sales@arcondec.mx",
    "mail_rh": "rh@arcondec.mx",
    "mail_quejas": "quejasysugerencias@arcondec.mx",
    "mail_proveedores": "proveedores@arcondec.mx",
    "mail_talento": "talento@arcondec.mx",
    "maps": "https://www.google.com/maps/place/Grupo+Arcondec+S.A.+de+C.V./@25.7124378,-100.3761168,17z",
}

WHATSAPP = (
    "https://wa.me/525530326595?text=Hola,%20Estoy%20interesado%20en%20conocer%20m%C3%A1s"
    "%20sobre%20los%20servicios%20que%20ofrece%20GRUPO%20ARCONDEC.%20%C2%BFPodr%C3%ADan"
    "%20proporcionarme%20informaci%C3%B3n%20adicional%3F%20Agradezco%20de%20antemano%20su"
    "%20atenci%C3%B3n."
)

SOCIAL = [
    ("facebook-f", "Facebook", "https://www.facebook.com/grupoarcondec"),
    ("instagram", "Instagram", "https://www.instagram.com/grupoarcondec"),
    ("linkedin-in", "LinkedIn", "https://www.linkedin.com/company/grupoarcondec/"),
    ("youtube", "YouTube", "https://www.youtube.com/@GRUPO_ARCONDEC"),
]

PRIVACY_PDF = "https://www.arcondec.mx/AvisoPrivacidad.pdf"
LOGIN_URL = "https://apps.arcondec.mx/"
VIDEO_URL = "https://www.youtube.com/watch?v=Q9PNm51CVK8"

# --------------------------------------------------------------------------
# Los 7 servicios. `key` da el nombre de las fotos: servicios/<key>-N.jpg
# --------------------------------------------------------------------------
SERVICES = [
    {
        "key": "proele",
        "photos": [1, 2, 3, 4, 5, 6, 7, 8, 9],
        "group": "ie",
        "icon": "fal fa-bolt",
        "slug": {"es": "proyectos-electricos-integrales", "en": "electrical-projects"},
        "es": {
            "nav": "Proyectos eléctricos",
            "title": "Proyectos eléctricos integrales",
            "meta": "Desarrollamos proyectos eléctricos integrales: diseño de redes de tierras, estudios eléctricos y servicios AC/DC, con más de 30 años de experiencia.",
            "keywords": "proyectos eléctricos, redes de tierras, estudios eléctricos, servicios AC, servicios DC, ingeniería eléctrica, Grupo Arcondec, infraestructura crítica",
            "h1": "Proyectos eléctricos integrales",
            "lead": "Soluciones eléctricas de alto desempeño, listas para operar desde el primer día",
            "tagline": "Ingeniería a la medida de tu operación",
            "intro_h2": "Soluciones llave en mano",
            "intro": "Están diseñados para brindarte total certeza técnica, diagnósticos precisos y documentación completa para el desarrollo, validación o mantenimiento de tus instalaciones eléctricas. Contamos con experiencia en proyectos desde 225 kVA hasta más de 2.5 MVA, atendiendo necesidades en plantas industriales, centros logísticos, complejos comerciales y desarrollos de alta demanda energética.",
            "list_title": "Servicios especializados",
            "list": [
                "Transformadores y subestaciones",
                "Tableros auto soportados y de distribución",
                "Diseño y desarrollo de ingeniería, instalación y puesta en marcha",
                "Todo conforme a normas NOM, CFE y NFPA",
                "UVIE (Unidad de Verificación de Instalaciones Eléctricas)",
                "Trámites y gestorías ante CFE",
            ],
            "benefits_title": "Impulsa tu operación con beneficios reales",
            "benefits_intro": "Al contratar un sistema eléctrico especializado, obtienes mucho más que infraestructura: accedes a seguridad operativa, eficiencia energética y respaldo técnico desde el primer día.",
            "benefits": [
                ("Acompañamiento técnico de principio a fin", "Te guiamos antes, durante y después de la implementación con soporte directo de nuestros ingenieros."),
                ("Agilidad en la ejecución, sin excusas", "Resolvemos rápido, ejecutamos con precisión y entregamos a tiempo. Tu proyecto no se detiene."),
                ("Menos riesgos, más control", "Evita fallas, paros inesperados y problemas normativos. Diseñamos pensando en la seguridad total de tu operación."),
            ],
            "cta_title": "Inicia tu proyecto eléctrico industrial con una solución profesional",
            "cta_text": "Recibe una asesoría técnica con nuestros especialistas y descubre cómo diseñar, optimizar o ejecutar tu sistema eléctrico de forma segura, eficiente y conforme a norma.",
        },
        "en": {
            "nav": "Electrical Projects",
            "title": "Comprehensive Electrical Projects",
            "meta": "We develop comprehensive electrical projects: grounding network design, electrical studies and AC/DC services, backed by over 30 years of experience.",
            "keywords": "electrical projects, grounding networks, electrical studies, AC services, DC services, electrical engineering, Grupo Arcondec, critical infrastructure",
            "h1": "Comprehensive electrical projects",
            "lead": "High-performance electrical solutions, ready to operate from day one",
            "tagline": "Engineering tailored to your operations",
            "intro_h2": "Turnkey solutions",
            "intro": "Designed to provide you with complete technical assurance, accurate diagnostics, and full documentation for the development, validation, or maintenance of your electrical installations. We have experience in projects ranging from 225 kVA to over 2.5 MVA, meeting the needs of industrial plants, logistics centers, commercial complexes, and developments with high energy demand.",
            "list_title": "Specialized Services",
            "list": [
                "Transformers and Substations",
                "Free-standing and Distribution Panels",
                "Engineering Design and Development, Installation and Commissioning",
                "All in compliance with NOM, CFE, and NFPA standards",
                "UVIE (Electrical Installations Verification Unit)",
                "Procedures and Management before CFE",
            ],
            "benefits_title": "Boost your operations with real benefits",
            "benefits_intro": "By hiring a specialized electrical system, you gain much more than just infrastructure: you access operational safety, energy efficiency, and technical support from day one.",
            "benefits": [
                ("Technical support and guidance from start to finish", "We guide you before, during, and after implementation with direct support from our engineers."),
                ("Agility in execution, no excuses", "We solve quickly, execute with precision, and deliver on time. Your project doesn’t stop."),
                ("Less risk, more control", "Avoid failures, unexpected shutdowns, and compliance issues. We design with your operation’s total safety in mind."),
            ],
            "cta_title": "Start your industrial electrical project with a professional solution",
            "cta_text": "Receive technical advice from our specialists and discover how to design, optimize, or execute your electrical system safely, efficiently, and in full compliance with standards.",
        },
    },
    {
        "key": "estel",
        "photos": [3, 5, 6, 7],
        "group": "ie",
        "icon": "fal fa-chart-line",
        "slug": {"es": "estudios-electricos-especializados", "en": "electrical-studies"},
        "es": {
            "nav": "Estudios eléctricos",
            "title": "Estudios eléctricos especializados",
            "meta": "Estudios eléctricos especializados: sistemas de tierras, calidad de energía, Arc Flash y coordinación de protecciones para una infraestructura segura.",
            "keywords": "estudios eléctricos, sistema de tierras, calidad de energía, arco eléctrico, coordinación de protecciones, Grupo Arcondec, ingeniería eléctrica",
            "h1": "Estudios eléctricos especializados",
            "lead": "Asegura el cumplimiento normativo",
            "tagline": "Tu aliado técnico para garantizar continuidad",
            "intro_h2": "Desarrollamos diagnósticos precisos y entregamos documentación técnica completa",
            "intro": "Realizamos estudios eléctricos especializados que garantizan instalaciones seguras, eficientes y en cumplimiento con las normas más exigentes del sector. Ya sea en proyectos nuevos, ampliaciones o procesos de validación, te entregamos diagnósticos confiables y documentación técnica completa. Nuestra experiencia abarca desde ingeniería básica y de detalle hasta análisis de código de red, calidad de energía, coordinación de protecciones, Arc Flash y sistemas de tierra. Todo desarrollado bajo normativas como NOM-001-SEDE, NEC y NFPA 70E, garantizando respaldo legal, técnico y operativo. En entornos industriales y de misión crítica, somos el soporte que necesitas para mantener la continuidad operativa y proteger tu infraestructura frente a riesgos eléctricos.",
            "list_title": "Servicios especializados",
            "list": [
                "Desarrollo de ingeniería básica y de detalle",
                "Elaboración de memorias técnicas y memorias de cálculo",
                "Diagramas unifilares y multifilares",
                "Estudio de código de red y calidad de energía",
                "Cálculo de cortocircuito, coordinación de protecciones y Arc Flash",
                "Estudios de sistemas de tierra física y mediciones certificadas",
                "Justificación normativa con base en NOM-001-SEDE, NEC, NFPA 70E, entre otras",
            ],
            "benefits_title": "La importancia de un diagnóstico eléctrico especializado",
            "benefits_intro": "En instalaciones industriales o de misión crítica, un sistema eléctrico mal diseñado o sin validación puede representar riesgos operativos, pérdidas económicas y sanciones regulatorias. Un estudio eléctrico profesional no solo protege tus activos, también respalda decisiones estratégicas para la expansión o modernización de tu sistema.",
            "benefits": [
                ("Cumplimiento normativo asegurado", "Nuestros estudios se desarrollan conforme a NOM-001-SEDE, NEC y NFPA 70E, facilitando auditorías, inspecciones y trámites ante CFE, CRE y UVIE."),
                ("Continuidad operativa sin interrupciones", "Detectamos riesgos eléctricos, deficiencias en protecciones y condiciones críticas que podrían ocasionar paros imprevistos."),
                ("Base técnica para toma de decisiones", "Entregamos documentación técnica clara, cálculos precisos y diagramas confiables que permiten planificar expansiones, mejoras o nuevas instalaciones."),
            ],
            "cta_title": "Solicita tu diagnóstico técnico",
            "cta_text": "Recibe una revisión preliminar de tu instalación para identificar riesgos y oportunidades de mejora.",
        },
        "en": {
            "nav": "Electrical Studies",
            "title": "Specialized Electrical Studies",
            "meta": "Specialized electrical studies: grounding systems, power quality, arc flash and protection coordination for safe, efficient infrastructure.",
            "keywords": "electrical studies, grounding system, power quality, arc flash, protection coordination, Grupo Arcondec, electrical engineering",
            "h1": "Specialized electrical studies",
            "lead": "Ensure regulatory compliance",
            "tagline": "Your technical partner to ensure continuity",
            "intro_h2": "We deliver accurate diagnostics and complete technical documentation",
            "intro": "We carry out specialized electrical studies that guarantee safe, efficient installations that meet the industry's highest standards. Whether for new projects, expansions, or validation processes, we provide reliable diagnostics and full technical documentation. Our experience ranges from basic and detailed engineering to grid code analysis, power quality, protection coordination, Arc Flash studies, and grounding systems. All developed in accordance with standards such as NOM-001-SEDE, NEC, and NFPA 70E, ensuring legal, technical, and operational support. In industrial and mission-critical environments, we are the support you need to maintain operational continuity and protect your infrastructure from electrical risks.",
            "list_title": "Specialized Services",
            "list": [
                "Basic and detailed engineering development",
                "Preparation of technical reports and calculation memos",
                "Single-line and multi-line diagrams",
                "Grid code and power quality study",
                "Short-circuit calculation, protection coordination, and Arc Flash analysis",
                "Grounding system studies and certified measurements",
                "Regulatory justification based on NOM-001-SEDE, NEC, NFPA 70E, among others",
            ],
            "benefits_title": "The importance of a specialized electrical diagnosis",
            "benefits_intro": "In industrial or mission-critical facilities, a poorly designed or unvalidated electrical system can pose operational risks, financial losses, and regulatory penalties. A professional electrical study not only protects your assets but also supports strategic decisions for the expansion or modernization of your system.",
            "benefits": [
                ("Guaranteed Regulatory Compliance", "Our studies are developed in accordance with NOM-001-SEDE, NEC, and NFPA 70E, facilitating audits, inspections, and procedures with CFE, CRE, and UVIE."),
                ("Uninterrupted Operational Continuity", "We identify electrical risks, protection deficiencies, and critical conditions that could cause unexpected shutdowns."),
                ("Technical Foundation for Decision-Making", "We provide clear technical documentation, accurate calculations, and reliable diagrams to support planning of expansions, upgrades, or new installations."),
            ],
            "cta_title": "Request your technical diagnosis",
            "cta_text": "Receive a preliminary assessment of your installation to identify risks and improvement opportunities.",
        },
    },
    {
        "key": "corac",
        "photos": [1, 2, 3, 4, 5, 6, 7],
        "group": "ie",
        "icon": "fal fa-battery-bolt",
        "slug": {"es": "soluciones-corriente-directa-dc", "en": "direct-current-solutions"},
        "es": {
            "nav": "Corriente directa (DC)",
            "title": "Soluciones en corriente directa (DC)",
            "meta": "Sistemas de corriente directa (DC): diseño, instalación, bancos de baterías, tableros DC y mantenimiento para infraestructura crítica y data centers.",
            "keywords": "corriente directa, sistemas DC, baterías, tableros DC, UPS, mantenimiento eléctrico, infraestructura crítica, Grupo Arcondec",
            "h1": "Soluciones en corriente directa (DC)",
            "lead": "Energía sin interrupciones para entornos donde no se puede fallar",
            "tagline": "Corriente directa ideal para tu proyecto",
            "intro_h2": "Garantizamos continuidad operativa",
            "intro": "Diseñamos, suministramos e implementamos sistemas de corriente directa (DC) que garantizan energía continua, segura y conforme a norma para aplicaciones críticas. Nuestra experiencia abarca desde centros de datos hasta instalaciones industriales que requieren máxima disponibilidad operativa 24/7.",
            "list_title": "Servicios especializados",
            "list": [
                "Distribuidores de Corriente Directa (BDCBB)",
                "Bancos de baterías de litio",
                "Plantas de corriente directa (PDC)",
                "Inversores y rectificadores",
                "Sistemas UPS",
            ],
            "benefits_title": "Impulsa tu operación con beneficios reales",
            "benefits_intro": "Elegir un sistema eléctrico especializado significa seguridad operativa, eficiencia energética y respaldo técnico desde el primer día.",
            "benefits": [
                ("Acompañamiento técnico de principio a fin", "Te guiamos antes, durante y después de la implementación con soporte directo de nuestros ingenieros."),
                ("Agilidad en la ejecución, sin excusas", "Resolvemos rápido, ejecutamos con precisión y entregamos a tiempo. Tu proyecto no se detiene."),
                ("Menos riesgos, más control", "Evita fallas, paros inesperados y problemas normativos. Diseñamos pensando en la seguridad total de tu operación."),
            ],
            "cta_title": "Inicia tu proyecto eléctrico industrial con una solución profesional",
            "cta_text": "Recibe una asesoría técnica con nuestros especialistas y descubre cómo diseñar, optimizar o ejecutar tu sistema eléctrico de forma segura, eficiente y conforme a norma.",
        },
        "en": {
            "nav": "Direct Current (DC)",
            "title": "Direct Current (DC) Solutions",
            "meta": "Direct current (DC) systems: design, installation, battery banks, DC panels and maintenance for critical infrastructure and data centers.",
            "keywords": "direct current, DC systems, batteries, DC panels, UPS, electrical maintenance, critical infrastructure, Grupo Arcondec",
            "h1": "Direct current (DC) solutions",
            "lead": "Uninterrupted power for environments where failure is not an option",
            "tagline": "Direct current tailored to your project",
            "intro_h2": "We ensure operational continuity",
            "intro": "We design, supply, and implement direct current (DC) systems that provide continuous, safe, and code-compliant power for critical applications. Our experience ranges from data centers to industrial facilities that demand maximum 24/7 operational availability.",
            "list_title": "Specialized Services",
            "list": [
                "Direct Current Distribution Bays (BDCBB)",
                "Lithium Battery Banks",
                "Direct Current Plants (PDC)",
                "Inverters and Rectifiers",
                "UPS Systems (Uninterruptible Power Supply Systems)",
            ],
            "benefits_title": "Boost your operations with real benefits",
            "benefits_intro": "Choosing a specialized electrical system means operational safety, energy efficiency, and technical support from day one.",
            "benefits": [
                ("Technical support from start to finish", "We guide you before, during, and after implementation with direct support from our engineers."),
                ("Agility in execution, no excuses", "We respond quickly, execute with precision, and deliver on time. Your project doesn't stop."),
                ("Fewer risks, more control", "Avoid failures, unexpected shutdowns, and regulatory issues. We design with the total safety of your operation in mind."),
            ],
            "cta_title": "Start your industrial electrical project with a professional solution",
            "cta_text": "Receive technical advice from our specialists and discover how to design, optimize, or execute your electrical system safely, efficiently, and in compliance with regulations.",
        },
    },
    {
        "key": "gespr",
        "photos": [1, 2, 3, 4, 5, 6, 7, 8],
        "group": "ie",
        "icon": "fal fa-tasks",
        "slug": {"es": "gestion-integral-proyectos-electricos", "en": "project-management"},
        "es": {
            "nav": "Gestión de proyectos",
            "title": "Gestión integral de proyectos eléctricos",
            "meta": "Gestión integral de proyectos eléctricos: tiempos, documentación, supervisión técnica y cumplimiento normativo para data centers e industria.",
            "keywords": "gestión de proyectos, project management, supervisión técnica, documentación técnica, infraestructura crítica, Grupo Arcondec",
            "h1": "Gestión integral de proyectos eléctricos",
            "lead": "Garantizamos control total en cada fase de tu obra",
            "tagline": "Tu proyecto en un caso de éxito",
            "intro_h2": "De la idea a la entrega, sin complicaciones",
            "intro": "Gestionamos cada proyecto con precisión técnica y visión integral, alineando tiempos, disciplinas y documentación desde el primer día. Nuestro enfoque va más allá de supervisar: anticipamos problemas, proponemos soluciones y aseguramos el cumplimiento de normas nacionales e internacionales. Nos especializamos en entornos donde la continuidad operativa es esencial: centros de datos, plantas industriales, telecomunicaciones y sistemas 24/7. Coordinamos de forma eficaz a todos los involucrados —desde ingenierías hasta contratistas— asegurando que cada plano, cada memoria y cada avance cumpla estándares como la NOM-001-SEDE, NEC y NFPA 70E. Esto se traduce en obras sin retrabajos, documentación aprobada sin observaciones y un cierre exitoso, tanto técnico como administrativo. Con nuestra gestión, tu inversión está respaldada. Recibes expedientes completos, planos as-built, reportes técnicos y actas firmadas que acreditan cada avance. Pero más importante aún: ganas tranquilidad al saber que tu proyecto está en manos de expertos que cuidan cada detalle como si fuera propio. Porque no se trata solo de construir, sino de entregar infraestructura lista para operar con seguridad, eficiencia y confiabilidad.",
            "list_title": "Servicios especializados",
            "list": [
                "Planeación Estratégica y Estimación Técnica",
                "Elaboración de catálogos, memorias técnicas y planos As-Built",
                "Supervisión Técnica y Coordinación Interdisciplinaria",
                "Entrega Documental y Cierre del Proyecto",
            ],
            "benefits_title": "Brindamos acompañamiento técnico real, tanto en sitio como a distancia, con respuestas inmediatas y decisiones fundamentadas",
            "benefits_intro": "Cada proyecto es tratado con rigor técnico, control documental y acompañamiento real. Mientras otros solo supervisan, nosotros gestionamos integralmente: conectamos ingeniería, normatividad y ejecución con enfoque en resultados medibles y sostenibles. Aquí, tu proyecto no es uno más: es una prioridad.",
            "benefits": [
                ("Control total del proyecto desde el inicio", "Planificación detallada, seguimiento técnico constante y coordinación entre disciplinas para asegurar que cada etapa avance sin contratiempos."),
                ("Acompañamiento técnico en cada fase", "Para resolver imprevistos, supervisar ejecución y garantizar la correcta interpretación de la ingeniería."),
                ("Trazabilidad y transparencia en cada entrega", "Cada actividad y decisión queda registrada, asegurando claridad para el cliente y control de calidad durante toda la ejecución."),
            ],
            "cta_title": "Atendemos proyectos en todo México y Latinoamérica",
            "cta_text": "Agenda una asesoría, uno de nuestros especialistas se pondrá en contacto contigo para conocer tu proyecto y proponerte una solución a la medida.",
        },
        "en": {
            "nav": "Project Management",
            "title": "Comprehensive Electrical Project Management",
            "meta": "Comprehensive electrical project management: schedules, documentation, technical supervision and regulatory compliance for data centers and industry.",
            "keywords": "project management, electrical project coordination, technical supervision, technical documentation, critical infrastructure, Grupo Arcondec",
            "h1": "Comprehensive electrical project management",
            "lead": "We ensure total control at every stage of your project",
            "tagline": "Your project, a success story",
            "intro_h2": "From concept to delivery, without complications",
            "intro": "We manage each project with technical precision and a comprehensive vision, aligning timelines, disciplines, and documentation from day one. Our approach goes beyond supervision: we anticipate issues, propose solutions, and ensure compliance with national and international standards. We specialize in environments where operational continuity is critical—data centers, industrial plants, telecommunications, and 24/7 systems. We effectively coordinate all parties involved —from engineering teams to contractors— ensuring that every plan, every report, and every milestone complies with standards such as NOM-001-SEDE, NEC, and NFPA 70E. This results in projects with no rework, fully approved documentation, and successful technical and administrative closure. With our project management, your investment is protected. You receive complete documentation, as-built plans, technical reports, and signed records that certify each milestone. More importantly, you gain peace of mind knowing your project is in expert hands, with attention to every detail as if it were our own. Because it's not just about building—it's about delivering infrastructure that is ready to operate safely, efficiently, and reliably.",
            "list_title": "Specialized Services",
            "list": [
                "Strategic Planning and Technical Estimation",
                "Preparation of Catalogs, Technical Reports, and As-Built Drawings",
                "Technical Supervision and Interdisciplinary Coordination",
                "Document Handover and Project Closeout",
            ],
            "benefits_title": "We provide real technical support, both on-site and remotely, with immediate responses and well-founded decisions.",
            "benefits_intro": "Each project is handled with technical rigor, thorough documentation control, and hands-on support. While others only supervise, we manage comprehensively—connecting engineering, compliance, and execution with a focus on measurable and sustainable results. Here, your project is not just another one — it's a priority.",
            "benefits": [
                ("Total Project Control from Day One", "Detailed planning, continuous technical oversight, and cross-discipline coordination to ensure every phase progresses smoothly."),
                ("Technical Support at Every Stage", "To address unforeseen issues, oversee execution, and ensure proper interpretation of the engineering plans."),
                ("Traceability and Transparency in Every Delivery", "Every activity and decision is documented, ensuring clarity for the client and quality control throughout execution."),
            ],
            "cta_title": "We handle projects throughout Mexico and Latin America",
            "cta_text": "Schedule a consultation — one of our specialists will contact you to learn about your project and offer a tailored solution.",
        },
    },
    {
        "key": "cosdc",
        "photos": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "group": "dc",
        "icon": "fal fa-server",
        "slug": {"es": "construccion-data-center", "en": "data-center-construction"},
        "es": {
            "nav": "Construcción llave en mano",
            "title": "Construcción de data center llave en mano",
            "meta": "Construcción de data centers llave en mano: UPS, plantas de emergencia, sistemas contra incendio, climatización de precisión y monitoreo BMS/DCIM.",
            "keywords": "construcción data center, llave en mano, UPS, planta de emergencia, BMS, DCIM, infraestructura crítica, Grupo Arcondec",
            "h1": "Construcción de data center llave en mano",
            "lead": "Infraestructura crítica diseñada para máxima disponibilidad, eficiencia y control operativo",
            "tagline": "Ingeniería especializada para entornos de misión crítica",
            "intro_h2": "Implementamos soluciones integrales para la construcción de centros de datos",
            "intro": "Abarcando desde el diseño técnico hasta la entrega funcional y documentada. Cada componente es desarrollado conforme a las más estrictas normas nacionales e internacionales de operación, seguridad y continuidad. Atendemos proyectos para empresas que requieren disponibilidad 24/7, baja latencia, redundancia energética y monitoreo en tiempo real. Nuestra experiencia incluye centros financieros, plataformas digitales, servicios en la nube, telecomunicaciones, salud, industria y gobierno.",
            "list_title": "Servicios especializados",
            "list": [
                "Sistema de respaldo UPS (Uninterruptible Power Supply)",
                "Sistema contra incendios (detección temprana, supresión con gas limpio)",
                "Planta de emergencia con transferencia automática y sincronización",
                "Plantas de corriente directa (PDC) y tableros de distribución DC",
                "Inversores, rectificadores y bancos de baterías",
                "Sistema de tierras físicas y pararrayos",
                "Climatización de presión (IN-ROW, CRAC/CRAH) y confort",
                "Monitoreo inteligente (BMS / DCIM)",
                "Control de acceso, monitoreo y videovigilancia (CCTV/IP)",
                "Cableado estructurado categoría 6A o superior",
            ],
            "benefits_title": "Beneficios tangibles para tu operación",
            "benefits_intro": "Diseñar e implementar un Data Center va más allá de instalar equipos; implica proteger tu operación, garantizar continuidad 24/7 y asegurar que cada sistema funcione de manera óptima, segura y conforme a norma. Entendemos la complejidad de las operaciones empresariales modernas. Por eso, nuestros servicios están diseñados para ofrecer valor real desde el primer día, especialmente en sectores donde la disponibilidad y el rendimiento son esenciales. Estos son algunos de los beneficios reales que obtienen nuestros clientes al confiar en nosotros para la construcción de su infraestructura crítica:",
            "benefits": [
                ("Acompañamiento técnico de principio a fin", "Te guiamos desde el diseño hasta la implementación con soporte directo de nuestros ingenieros especialistas en infraestructura crítica."),
                ("Agilidad en la ejecución, sin excusas", "Coordinamos equipos, normativas y entregables para que tu data center avance sin fricciones ni retrasos."),
                ("Seguridad física y lógica desde el diseño", "Incorporamos soluciones de control de acceso, videovigilancia, sistemas contra incendios y segregación de espacios desde la ingeniería básica."),
            ],
            "cta_title": "Inicia tu proyecto de Data Center con una solución profesional",
            "cta_text": "Recibe una asesoría técnica con nuestros especialistas y descubre cómo diseñar, optimizar o construir tu centro de datos conforme a las mejores prácticas del sector.",
        },
        "en": {
            "nav": "Turnkey Construction",
            "title": "Turnkey Data Center Construction",
            "meta": "Turnkey data center construction: UPS, emergency power plants, fire protection, precision cooling and BMS/DCIM monitoring for 24/7 operation.",
            "keywords": "data center construction, turnkey, UPS, emergency power plant, BMS, DCIM, critical infrastructure, Grupo Arcondec",
            "h1": "Turnkey data center construction",
            "lead": "Critical infrastructure designed for maximum availability, efficiency, and operational control",
            "tagline": "Specialized engineering for mission-critical environments",
            "intro_h2": "We implement comprehensive solutions for data center construction",
            "intro": "Covering everything from technical design to functional and fully documented delivery. Every component is developed in compliance with the most rigorous national and international standards for operation, safety, and continuity. We serve projects for companies requiring 24/7 availability, low latency, energy redundancy, and real-time monitoring. Our experience includes financial centers, digital platforms, cloud services, telecommunications, healthcare, industry, and government.",
            "list_title": "Specialized Services",
            "list": [
                "UPS Backup System (Uninterruptible Power Supply)",
                "Fire protection system (early detection, clean agent suppression)",
                "Emergency power plant with automatic transfer and synchronization",
                "Direct Current Plants (PDC) and DC distribution panels",
                "Inverters, rectifiers, and battery banks",
                "Grounding systems and lightning protection",
                "Pressure and comfort cooling (IN-ROW, CRAC/CRAH)",
                "Smart monitoring (BMS / DCIM)",
                "Access control, monitoring and video surveillance (CCTV/IP)",
                "Structured cabling category 6A or higher",
            ],
            "benefits_title": "Tangible benefits for your operation",
            "benefits_intro": "Designing and implementing a Data Center goes beyond installing equipment; it means protecting your operations, ensuring 24/7 continuity, and guaranteeing that every system functions optimally, safely, and in full compliance with regulations. We understand the complexity of modern business operations. That’s why our services are designed to deliver real value from day one—especially in sectors where availability and performance are essential.",
            "benefits": [
                ("Technical support from start to finish", "We guide you from design to implementation with direct support from our critical infrastructure engineering specialists."),
                ("Fast execution, no excuses", "We coordinate teams, regulations, and deliverables so your data center progresses without friction or delays."),
                ("Physical and logical security by design", "We incorporate access control, video surveillance, fire protection, and space segregation solutions starting from the basic engineering phase."),
            ],
            "cta_title": "Start your Data Center project with a professional solution",
            "cta_text": "Get technical advice from our specialists and discover how to design, optimize, or build your data center according to industry best practices.",
        },
    },
    {
        "key": "civdc",
        "photos": [1, 2, 3, 4, 5, 6, 7, 8, 9],
        "group": "dc",
        "icon": "fal fa-drafting-compass",
        "slug": {"es": "ingenieria-civil-data-center", "en": "civil-engineering-data-center"},
        "es": {
            "nav": "Ingeniería civil",
            "title": "Ingeniería civil para centros de datos",
            "meta": "Obra civil para data centers: cimentación, piso falso en área blanca, confinamiento de pasillos y acabados conforme a TIA-942, NEC y NFPA.",
            "keywords": "ingeniería civil, data center, piso falso, área blanca, TIA-942, obra civil especializada, Grupo Arcondec",
            "h1": "Ingeniería civil para centros de datos",
            "lead": "Infraestructura física diseñada para soportar entornos de misión crítica con precisión estructural, funcional y operativa",
            "tagline": "Construcción de data centers de alta disponibilidad",
            "intro_h2": "Implementamos soluciones integrales para la construcción de centros de datos",
            "intro": "Contamos con experiencia en proyectos de infraestructura crítica que requieren precisión estructural, cumplimiento normativo y coordinación técnica en cada detalle constructivo. Implementamos obras civiles especializadas para centros de datos en cumplimiento con las normativas más exigentes: TIA-942, NOM, Uptime Institute, NEC, NFPA y especificaciones de fabricantes de equipamiento tecnológico. Nuestros procesos constructivos están diseñados para cumplir con los estándares de disponibilidad TIER I, TIER II, TIER III y TIER IV.",
            "list_title": "Servicios especializados",
            "list": [
                "Cimentación y obra estructural especializada",
                "Albañilería técnica y acabados industriales",
                "Cancelería, puertas con control de acceso, mamparas técnicas",
                "Confinamiento de espacios de línea y fabricación a medida",
                "Desarrollo de ingenierías",
                "Cálculos y memorias estructurales",
                "Instalaciones hidráulicas y sanitarias con requerimientos especiales",
                "Piso falso en Área Blanca",
                "Aislamiento térmico y acústico",
            ],
            "benefits_title": "Beneficios de trabajar con Grupo Arcondec",
            "benefits_intro": "Nuestra experiencia nos permite ejecutar obras con precisión, pensando no solo en la solidez del edificio, sino en la continuidad operativa del entorno tecnológico que va a soportar. Desarrollamos ingeniería civil especializada, con eficiencia energética y cumplimiento con estándares nacionales e internacionales. Cada solución que entregamos está diseñada para integrarse con los sistemas eléctricos, mecánicos y de TI de forma segura, funcional y validable ante cualquier auditoría.",
            "benefits": [
                ("Obra civil alineada a normativas", "Construimos, diseñamos con base en los requerimientos de TIA-942, NEC y NFPA, asegurando compatibilidad con infraestructura TI, control ambiental y seguridad física."),
                ("Ejecución técnica sin interrupciones ni improvisaciones", "Desde la cimentación hasta el piso falso y los aislamientos, cada elemento está coordinado con ingeniería, supervisión y pruebas, evitando retrabajos y entregas parciales."),
                ("Soluciones personalizadas para entornos de alta exigencia", "Desarrollamos espacios a medida: salas blancas, pasillos confinados, mamparas técnicas, cancelerías especiales y sanitarios adaptados, todo según las necesidades reales del cliente."),
            ],
            "cta_title": "Inicia tu proyecto de Data Center con una solución profesional",
            "cta_text": "Recibe una asesoría técnica con nuestros especialistas y descubre cómo diseñar, optimizar o construir tu centro de datos conforme a las mejores prácticas del sector.",
        },
        "en": {
            "nav": "Civil Engineering",
            "title": "Civil Engineering for Data Centers",
            "meta": "Civil works for data centers: foundations, raised floors in white areas, aisle containment and industrial finishes per TIA-942, NEC and NFPA.",
            "keywords": "civil engineering, data center, raised floor, white area, TIA-942, specialized civil works, Grupo Arcondec",
            "h1": "Civil engineering for data centers",
            "lead": "Physical infrastructure designed to support mission-critical environments with structural, functional, and operational precision",
            "tagline": "High-availability data center construction",
            "intro_h2": "We implement comprehensive solutions for data center construction",
            "intro": "We have experience in critical infrastructure projects that demand structural precision, regulatory compliance, and technical coordination in every construction detail. We execute specialized civil works for data centers in compliance with the most demanding standards: TIA-942, NOM, Uptime Institute, NEC, NFPA, and specifications from technology equipment manufacturers. Our construction processes are designed to meet TIER I, TIER II, TIER III, and TIER IV availability standards.",
            "list_title": "Specialized Services",
            "list": [
                "Specialized foundations and structural works",
                "Technical masonry and industrial-grade finishes",
                "Glazing systems, access-controlled doors, and technical partitions",
                "Line space containment and custom-built structures",
                "Engineering development",
                "Structural calculations and technical reports",
                "Hydraulic and sanitary installations with special requirements",
                "Raised floor in White Area",
                "Thermal and acoustic insulation",
            ],
            "benefits_title": "Benefits of working with Grupo Arcondec",
            "benefits_intro": "Our experience allows us to execute construction projects with precision, focusing not only on the structural integrity of the building but also on the operational continuity of the technological environment it will support. We develop specialized civil engineering with energy efficiency and compliance with national and international standards. Every solution we deliver is designed to integrate safely, functionally, and audit-ready with electrical, mechanical, and IT systems.",
            "benefits": [
                ("Civil works aligned with standards", "We build and design based on TIA-942, NEC, and NFPA requirements, ensuring compatibility with IT infrastructure, environmental control, and physical security."),
                ("Technical execution without interruptions or improvisation", "From foundations to raised flooring and insulation, every element is coordinated with engineering, supervision, and testing to avoid rework and partial deliveries."),
                ("Customized solutions for high-demand environments", "We develop tailor-made spaces: white rooms, confined aisles, technical partitions, special glasswork, and customized restrooms—all based on the client's real needs."),
            ],
            "cta_title": "Start your Data Center project with a professional solution",
            "cta_text": "Receive technical advice from our specialists and discover how to design, optimize, or build your data center according to industry best practices.",
        },
    },
    {
        "key": "ingdc",
        "photos": [1, 2, 3, 4, 5, 6, 7, 8],
        "group": "dc",
        "icon": "fal fa-cogs",
        "slug": {"es": "servicios-ingenieria-integral", "en": "engineering-services"},
        "es": {
            "nav": "Servicios de ingeniería",
            "title": "Servicios de ingeniería integral",
            "meta": "Ingeniería eléctrica, mecánica y civil para centros de datos conforme a TIA-942, Uptime Institute, NEC y NFPA 70E, con pruebas integrales de puesta en marcha.",
            "keywords": "servicios de ingeniería, ingeniería integral, TIA-942, Uptime Institute, commissioning, data center, Grupo Arcondec",
            "h1": "Servicios de ingeniería integral",
            "lead": "Nuestro trabajo va más allá del diseño",
            "tagline": "Ingeniería multidisciplinaria orientada a alta disponibilidad",
            "intro_h2": "Servicios de Ingeniería para Centros de Datos",
            "intro": "Enfoque especializado, alineado con los más altos estándares internacionales para garantizar operación continua, eficiencia energética y cumplimiento normativo. En Grupo Arcondec desarrollamos centros de datos e infraestructura crítica, abarcando disciplinas eléctrica, mecánica y civil. Nuestro enfoque se basa en los lineamientos del TIA-942, Uptime Institute, NEC, NFPA 70E y NOM-001-SEDE, asegurando que cada sistema esté diseñado para operar con redundancia, seguridad y disponibilidad 24/7.",
            "list_title": "Servicios especializados",
            "list": [
                "Diseño y desarrollo de ingeniería eléctrica, mecánica y civil conforme a estándares TIA-942 y Uptime Institute",
                "Memorias técnicas, diagramas unifilares, layout electromecánico",
                "Estudios de carga térmica, coordinación de protecciones, calidad de energía",
                "Supervisión de obra técnica y cumplimiento normativo",
                "Pruebas integrales de puesta en marcha (start-up, commissioning)",
            ],
            "benefits_title": "Valor estratégico de nuestra ingeniería",
            "benefits_intro": "Creamos y diseñamos soluciones de ingeniería con un enfoque de alta disponibilidad operativa (24/7) integrando sistemas redundantes y plenamente compatibles que aseguran la estabilidad, control, continuidad y operabilidad incluso en los entornos más críticos.",
            "benefits": [
                ("Cumplimiento normativo desde el diseño", "Todos nuestros proyectos están alineados con estándares internacionales (TIA-942, Uptime Institute, NEC, NFPA) y nacionales (NOM-001-SEDE), lo que minimiza riesgos legales, facilita auditorías regulatorias y acelera procesos de certificación."),
                ("Reducción de riesgos técnicos y costos futuros", "Una ingeniería bien ejecutada evita retrabajos, fallas operativas y paros imprevistos. Nuestra experiencia nos permite anticipar problemas, optimizar recursos y entregar documentación técnica sólida que respalda decisiones estratégicas a lo largo del ciclo de vida del data center."),
                ("Soluciones personalizadas para entornos de alta exigencia", "Desarrollamos espacios a medida: salas blancas, pasillos confinados, mamparas técnicas, cancelerías especiales y sanitarios adaptados, todo según las necesidades reales del cliente."),
            ],
            "cta_title": "Inicia tu proyecto de Data Center con una solución profesional",
            "cta_text": "Solicita una sesión técnica con nuestro equipo y descubre cómo podemos diseñar e implementar la base tecnológica que tu operación necesita.",
        },
        "en": {
            "nav": "Engineering Services",
            "title": "Comprehensive Engineering Services",
            "meta": "Electrical, mechanical and civil engineering for data centers per TIA-942, Uptime Institute, NEC and NFPA 70E, including commissioning testing.",
            "keywords": "engineering services, comprehensive engineering, TIA-942, Uptime Institute, commissioning, data center, Grupo Arcondec",
            "h1": "Comprehensive engineering services",
            "lead": "Our work goes beyond design",
            "tagline": "Multidisciplinary engineering focused on high availability",
            "intro_h2": "Engineering services for data centers",
            "intro": "A specialized approach aligned with the highest international standards to ensure continuous operation, energy efficiency, and regulatory compliance. At Grupo Arcondec, we develop data centers and critical infrastructure covering electrical, mechanical, and civil disciplines. Our approach is based on the guidelines of TIA-942, Uptime Institute, NEC, NFPA 70E, and NOM-001-SEDE, ensuring that each system is designed to operate with redundancy, safety, and 24/7 availability.",
            "list_title": "Specialized Services",
            "list": [
                "Design and development of electrical, mechanical, and civil engineering in accordance with TIA-942 and Uptime Institute standards",
                "Technical reports, single-line diagrams, and electromechanical layouts",
                "Thermal load studies, protection coordination, and power quality analysis",
                "Technical site supervision and regulatory compliance",
                "Comprehensive start-up and commissioning testing",
            ],
            "benefits_title": "Strategic value of our engineering",
            "benefits_intro": "We create and design engineering solutions with a high-availability (24/7) approach, integrating redundant and fully compatible systems that ensure stability, control, continuity, and operability—even in the most critical environments.",
            "benefits": [
                ("Regulatory Compliance From the Design Stage", "All our projects are aligned with international standards (TIA-942, Uptime Institute, NEC, NFPA) and national regulations (NOM-001-SEDE), minimizing legal risks, facilitating regulatory audits, and accelerating certification processes."),
                ("Reduced Technical Risks and Future Costs", "Well-executed engineering avoids rework, operational failures, and unexpected downtime. Our experience allows us to anticipate issues, optimize resources, and deliver robust technical documentation that supports strategic decisions throughout the data center lifecycle."),
                ("Tailored Solutions for High-Demand Environments", "We develop customized spaces: clean rooms, confined aisles, technical partitions, specialized enclosures, and adapted sanitary facilities—all according to the client’s real needs."),
            ],
            "cta_title": "Start your Data Center project with a professional solution",
            "cta_text": "Request a technical session with our team and discover how we can design and implement the technological foundation your operation needs.",
        },
    },
]

# --------------------------------------------------------------------------
# Listas de servicios que aparecen en el pie y en las paginas interiores
# --------------------------------------------------------------------------
LIST_IE = {
    "es": {
        "title": "Ingeniería Eléctrica",
        "items": [
            "Proyectos eléctricos",
            "Corriente alterna (AC) y directa (DC)",
            "Estudios eléctricos",
            "Servicios eléctricos",
            "Diseño de red de tierras",
            "Sistemas fotovoltaicos",
            "Mantenimiento eléctrico preventivo y correctivo",
        ],
    },
    "en": {
        "title": "Electrical Engineering",
        "items": [
            "Electrical Projects",
            "Alternating Current (AC) and Direct Current (DC)",
            "Electrical Studies",
            "Electrical Services",
            "Grounding Network Design",
            "Photovoltaic Systems",
            "Preventive and Corrective Electrical Maintenance",
        ],
    },
}

LIST_DC = {
    "es": {
        "title": "Data Centers",
        "items": [
            "Sistema de respaldo UPS (Power System)",
            "Instalación de tablero de distribución en corriente directa tipo BDCBB",
            "Generadores de emergencia",
            "Plantas de Corriente Directa",
            "Inversores y banco de baterías",
            "Sistema de tierras física y pararrayos",
        ],
    },
    "en": {
        "title": "Data Centers",
        "items": [
            "UPS Backup System (Power System)",
            "Direct Current Distribution Board Installation (BDCBB type)",
            "Emergency Generators",
            "Direct Current Plants",
            "Inverters and Battery Banks",
            "Grounding and Lightning Protection System",
        ],
    },
}

COMMIT_TEXT = {
    "es": "Fortalecemos cada día nuestro compromiso contigo, brindando un servicio excepcional como tu aliado estratégico en ingeniería eléctrica y centros de datos.",
    "en": "We strengthen our commitment to you every day by delivering exceptional service as your strategic partner in electrical engineering and data centers.",
}
