"""Desarrollo editorial propio; no añade hitos atribuidos a las fuentes."""
ANALYSIS = {
 'durango': {
  'es': [
   ('Del anuncio al programa de obra', 'Para interpretar un proyecto de esta escala conviene preguntar qué parte corresponde al plan completo y qué parte a una primera etapa. Un campus puede plantearse como una inversión de largo plazo, mientras sus edificios, servicios y áreas de soporte se incorporan gradualmente. Por eso, una cifra de capacidad no permite deducir por sí sola cuántos clientes podrá atender al inicio ni cuándo comenzará a operar. Esas respuestas requieren información específica del desarrollo.'),
   ('La coordinación empieza antes de construir', 'Como criterio de planeación, el programa del edificio debería revisarse junto con las necesidades de suministro, acceso y crecimiento. Por ejemplo, una primera etapa puede funcionar como una unidad independiente y, al mismo tiempo, reservar espacio para ampliaciones. La pregunta relevante es cómo se conectarán las fases posteriores sin convertir cada expansión en una modificación imprevista de lo ya entregado. Esta es una lectura editorial del anuncio, no una descripción del diseño particular del campus.'),
   ('Qué avances vale la pena seguir', 'El seguimiento de la noticia puede centrarse en hitos concretos: definición de etapas, inicio de trabajos, entrega de infraestructura y confirmación de operación. Cada uno responde a una pregunta distinta y debe documentarse por separado. Para empresas que evalúan oportunidades en nuevas regiones, ese orden ayuda a comparar expectativas con avances verificables. El interés industrial de Durango merece atención, pero su evolución debe medirse por decisiones ejecutadas y servicios disponibles, además de los anuncios de capacidad.')],
  'en': [
   ('From announcement to construction programme', 'To interpret a project of this scale, it helps to distinguish the overall plan from its initial phase. A campus may represent a long-term investment while buildings, services and support areas are introduced gradually. A capacity figure alone therefore cannot establish how many customers the first phase will serve or when operations will begin. Those questions require development-specific information rather than assumptions based on the headline.'),
   ('Coordination starts before construction', 'As a planning principle, the building programme should be considered alongside power, access and growth requirements. An initial phase might operate independently while reserving space for expansion. The important question is how later phases will connect without turning every expansion into an unplanned alteration of completed infrastructure. This is an editorial interpretation of the announcement, not a description of the campus’s actual design.'),
   ('Which milestones deserve attention', 'Following the story means looking for concrete milestones: defined phases, construction starts, infrastructure handover and confirmed operations. Each answers a different question and should be documented separately. For businesses evaluating new regions, this approach helps compare expectations with verifiable progress. Durango’s industrial prospects deserve attention, but their development should be assessed through executed decisions and available services as well as capacity announcements.')]
 },
 'densidad-talento': {
  'es': [
   ('La densidad no se resume en un promedio', 'Como ejercicio de planeación, imaginemos una sala con cargas convencionales y una zona de cómputo intensivo. Un promedio general puede ocultar diferencias importantes entre ambas. Antes de proponer una ampliación, resulta útil describir dónde se espera el crecimiento, qué equipos cambiarán y qué condiciones deben conservarse en las áreas existentes. Esta forma de plantear el problema permite una conversación más precisa entre quienes solicitan capacidad y quienes diseñan la infraestructura que la soporta.'),
   ('El talento forma parte del proyecto', 'La preparación del personal no tendría que aparecer únicamente al final de la obra. Una propuesta de trabajo puede incluir revisión de documentos, familiarización con los equipos y participación del equipo operativo en la entrega. El objetivo editorial que planteamos es sencillo: que la instalación no dependa de explicaciones informales o del conocimiento concentrado en una sola persona. Los cambios de turno y la incorporación de nuevos técnicos son momentos útiles para evaluar si la información realmente se entiende.'),
   ('Modernizar con prioridades claras', 'Una ruta razonable para discutir la modernización es separar necesidades inmediatas, crecimiento previsto y opciones futuras. No todo escenario requiere ejecutarse al mismo tiempo. Esa distinción ayuda a explicar por qué se elige una fase de inversión y qué condiciones justificarían la siguiente. La encuesta ofrece contexto para abrir estas conversaciones; las decisiones de una instalación concreta deben apoyarse en sus propias cargas, restricciones y objetivos de servicio.')],
  'en': [
   ('Density cannot be reduced to an average', 'As a planning exercise, consider a room with conventional workloads and a separate intensive-computing area. One overall average could conceal important differences. Before proposing expansion, it is useful to describe where growth is expected, which equipment will change and which conditions must remain in existing areas. Framing the issue this way enables a more precise discussion between the people requesting capacity and those designing the infrastructure to support it.'),
   ('Talent belongs in the project scope', 'Staff preparation need not appear only at the end of construction. A work programme could include document reviews, equipment familiarisation and operational participation in handover. The editorial objective is straightforward: the facility should not rely on informal explanations or knowledge concentrated in one person. Shift changes and onboarding new technicians are useful opportunities to assess whether the information is genuinely understandable.'),
   ('Modernising with clear priorities', 'One useful way to discuss modernisation is to separate immediate needs, expected growth and future options. Not every scenario has to be implemented at once. This distinction helps explain why an investment phase is selected and what would justify the next one. The survey provides context for these conversations; decisions for an individual facility should draw on its own workloads, constraints and service objectives.')]
 },
 'queretaro': {
  'es': [
   ('Un predio disponible no es un proyecto resuelto', 'La superficie y la ubicación son un punto de partida, pero no explican por completo la conveniencia de un terreno. En una evaluación preliminar conviene separar lo que ya existe de lo que todavía debe desarrollarse. También es útil identificar quién aportará cada servicio y qué decisiones dependen de terceros. Esta distinción evita presentar como una sola fecha procesos que pueden avanzar a ritmos diferentes. Se trata de un criterio de análisis, no de una evaluación de predios específicos en Querétaro.'),
   ('Pensar en el funcionamiento cotidiano', 'Además de imaginar el edificio terminado, proponemos revisar cómo se utilizará durante su vida operativa. ¿Cómo llegarán los equipos de reemplazo? ¿Qué espacios deberán permanecer accesibles? ¿Cómo se incorporará una nueva etapa? Estas preguntas permiten comparar alternativas con una perspectiva más amplia que la ocupación inicial del terreno. Un sitio atractivo para construir merece también una revisión de las condiciones necesarias para mantenerlo, adaptarlo y hacerlo crecer.'),
   ('Del crecimiento regional a las decisiones concretas', 'Para propietarios, desarrolladores y equipos de ingeniería, el interés del mercado puede convertirse en una oportunidad de coordinación. Una agenda compartida de dependencias, responsables y puntos pendientes ayuda a ordenar la conversación antes de comprometer fechas. El desarrollo industrial asociado a los centros de datos no debe leerse únicamente como demanda de edificios: también abre una discusión sobre la infraestructura que permite utilizarlos. El avance de cada proyecto tendrá que comprobarse con información particular y actualizada.')],
  'en': [
   ('Available land is not a completed project plan', 'Area and location are a starting point, but they do not fully explain a site’s suitability. A preliminary assessment should distinguish what already exists from what still needs development. It is also useful to identify who will provide each service and which decisions depend on third parties. This prevents processes moving at different speeds from being represented by a single date. This is an analytical approach, not an assessment of particular sites in Querétaro.'),
   ('Considering everyday operations', 'Beyond imagining the finished building, we suggest considering how it will be used throughout its operational life. How will replacement equipment arrive? Which spaces must remain accessible? How could another phase be added? These questions allow alternatives to be compared beyond initial land occupation. A site that is attractive for construction also deserves an assessment of the conditions needed to maintain, adapt and expand the facility.'),
   ('From regional growth to specific decisions', 'For owners, developers and engineering teams, market interest can become an opportunity for coordination. A shared record of dependencies, responsibilities and unresolved issues helps structure discussions before dates are committed. Industrial development associated with data centers is not only a matter of demand for buildings: it also raises questions about the infrastructure that makes them usable. Each project’s progress will need to be established through current, project-specific information.')]
 },
 'continuidad': {
  'es': [
   ('La disponibilidad también se gestiona', 'En términos de organización, una instalación necesita acuerdos claros sobre quién decide, quién interviene y quién recibe información cuando cambia una condición. Un inventario de equipos no responde por sí solo esas preguntas. Como lectura editorial, proponemos revisar la continuidad desde las actividades cotidianas: cambios de turno, trabajos programados, seguimiento de pendientes y comunicación entre áreas. El propósito es reconocer cómo una decisión local puede afectar a otras partes de la operación.'),
   ('Aprender de los incidentes sin simplificarlos', 'Atribuir un evento a una sola pieza o a una sola persona puede dejar preguntas importantes sin resolver. Un análisis útil debería reconstruir el contexto, las condiciones conocidas y la información disponible en cada momento. También conviene distinguir las causas del evento de los factores que hicieron más lenta su recuperación. Esta perspectiva no sustituye una investigación técnica; plantea una forma de organizar sus resultados para que las acciones posteriores tengan responsables y seguimiento.'),
   ('De la documentación a la práctica', 'Un procedimiento aporta valor cuando el equipo puede encontrarlo, comprenderlo y reconocer cuándo aplica. Por ello, una revisión documental puede acompañarse de ejercicios de conversación y evaluación de escenarios con personal competente, sin improvisar maniobras sobre sistemas en servicio. La meta es comprobar que las responsabilidades y los canales de comunicación estén claros. La continuidad se convierte así en un trabajo sostenido, no solamente en una característica declarada al entregar la instalación.')],
  'en': [
   ('Availability also requires management', 'From an organisational perspective, a facility needs clear agreements about who decides, who intervenes and who receives information when conditions change. An equipment inventory alone cannot answer these questions. Our editorial suggestion is to examine continuity through everyday activities: shift changes, scheduled work, outstanding tasks and communication across teams. The aim is to understand how a local decision can affect other parts of the operation.'),
   ('Learning from incidents without oversimplifying them', 'Attributing an event to one component or one person can leave important questions unanswered. A useful review should reconstruct the context, known conditions and information available at each stage. It should also distinguish the causes of the event from factors that delayed recovery. This perspective does not replace a technical investigation; it offers a way to organise findings so subsequent actions have clear ownership and follow-up.'),
   ('From documentation to practice', 'A procedure is useful when staff can locate it, understand it and recognise when it applies. Document review can therefore be accompanied by discussions and scenario assessments with competent personnel, without improvising interventions on live systems. The goal is to establish whether responsibilities and communication channels are clear. Continuity then becomes an ongoing organisational task, rather than simply a characteristic declared at handover.')]
 },
 'energia-ia': {
  'es': [
   ('Distinguir potencia, consumo y crecimiento', 'Al leer anuncios del sector conviene prestar atención a qué se está midiendo. Una capacidad prevista, un consumo observado y una proyección de demanda describen cosas diferentes. Mezclarlas puede llevar a conclusiones equivocadas sobre el tamaño o el avance de un desarrollo. En esta noticia, las cifras citadas describen un cambio global de consumo; no permiten calcular directamente la demanda de una ciudad mexicana o de un nuevo campus.'),
   ('Coordinar el horizonte digital y el físico', 'Como planteamiento editorial, la expansión tecnológica debería discutirse junto con los plazos de la infraestructura que la hará posible. Un programa puede ordenar decisiones sobre edificio, equipos, servicios y operación, dejando explícitas sus dependencias. La pregunta no es solamente cuánta capacidad se desea alcanzar, sino qué debe estar disponible antes de cada etapa. Esta forma de presentar el proyecto facilita explicar los supuestos y revisar el calendario cuando alguno cambia.'),
   ('Qué significa para la conversación en México', 'El contexto internacional ayuda a formular preguntas locales, pero no las responde automáticamente. Cada iniciativa debe aclarar su ubicación, su escala, su demanda prevista y las condiciones que necesita para operar. Para seguir la industria con rigor, proponemos comparar datos del mismo alcance y distinguir las estimaciones de las mediciones. Así, la discusión sobre inteligencia artificial puede pasar de cifras generales a decisiones de planeación que tengan sentido para un proyecto concreto.')],
  'en': [
   ('Distinguishing capacity, consumption and growth', 'When reading industry announcements, it matters what is being measured. Planned capacity, observed consumption and demand forecasts describe different things. Combining them can lead to incorrect conclusions about a development’s scale or progress. The figures cited in this story describe a global consumption change; they cannot directly establish demand for a Mexican city or a new campus.'),
   ('Coordinating digital and physical timelines', 'Our editorial view is that technological expansion should be discussed alongside the infrastructure timelines that make it possible. A programme can organise decisions about buildings, equipment, services and operations while making their dependencies explicit. The question is not only how much capacity is desired, but what must be available before each phase. Presenting a project this way makes assumptions easier to explain and schedules easier to reassess when those assumptions change.'),
   ('What this means for discussions in Mexico', 'International context helps frame local questions, but it does not answer them automatically. Each initiative needs to establish its location, scale, expected demand and operating requirements. To follow the industry carefully, we suggest comparing figures with equivalent scope and distinguishing estimates from measurements. This allows discussion of artificial intelligence to move beyond headline numbers towards planning decisions that make sense for a particular project.')]
 },
 'nube-publica': {
  'es': [
   ('Una plataforma compartida necesita acuerdos', 'La idea de reunir capacidades públicas plantea una conversación que va más allá de los equipos. Como análisis editorial, resulta útil preguntar qué instituciones utilizarán la plataforma, quién administrará sus recursos y cómo se priorizarán nuevas solicitudes. También conviene definir qué información permitirá evaluar el servicio. Estas preguntas no describen acuerdos ya adoptados por NubeMX; son aspectos que ayudan a interpretar el alcance de una iniciativa de infraestructura compartida.'),
   ('Separar construcción y adopción', 'La disponibilidad de un edificio o de nuevos equipos es un hito distinto de la incorporación efectiva de servicios. Entre ambos pueden existir actividades de preparación, coordinación y validación. Para comunicar los avances con claridad, proponemos distinguir la entrega física, la habilitación de la plataforma y el uso por parte de las instituciones. De ese modo, un anuncio sobre infraestructura no se confunde con la conclusión de todo el proceso de transformación digital.'),
   ('Cómo dar seguimiento a la agenda', 'El seguimiento puede organizarse alrededor de preguntas verificables: qué etapa se anunció, qué entregable se confirmó y qué instituciones participan. Cuando no exista una actualización oficial, es preferible mantener el hito como programado en lugar de asumir que ya ocurrió. Esta disciplina editorial permite observar el desarrollo de la nube pública sin confundir objetivos con resultados. La relevancia de la agenda estará en cómo sus capacidades se traduzcan en servicios utilizables y sostenidos en el tiempo.')],
  'en': [
   ('A shared platform needs clear agreements', 'Bringing public computing capabilities together raises questions beyond equipment. As an editorial analysis, it is useful to ask which institutions will use the platform, who will manage resources and how new requests will be prioritised. It is also worth defining what information will be used to assess the service. These questions do not describe agreements already adopted by NubeMX; they help frame the scope of a shared infrastructure initiative.'),
   ('Separating construction from adoption', 'Having a building or new equipment available is a different milestone from bringing services into actual use. Preparation, coordination and validation may take place between those stages. To communicate progress clearly, we suggest distinguishing physical handover, platform readiness and institutional adoption. This prevents an infrastructure announcement from being mistaken for completion of the entire digital transformation process.'),
   ('Following the agenda over time', 'Progress can be tracked through verifiable questions: which phase was announced, which deliverable was confirmed and which institutions are involved. Without an official update, a milestone should remain scheduled rather than being assumed complete. This editorial discipline makes it possible to follow public cloud development without confusing objectives with outcomes. The agenda’s significance will depend on how its capabilities translate into usable services sustained over time.')]
 }
}
